#!/bin/bash

# getDoc
# 2019 GUILLEUS Hugues <ghugues@netc.fr>
# BSD 3-Clause "New" or "Revised" License

clear

# Style files
cat style/*.css | tr '\t\n' ' ' |
	# sed -E 's#[^/]\*[^/]##g' | sed -E 's#/\*[^*]*\*/# #g' |
	sed -E 's# +# #g' | sed -E 's#([:;{}]) #\1#g' |
	sed 's#^#\t<style>#' | sed 's#$#</style>\n#' > include.html

# JavaScript files
JS_NOLETTER=':;,.()<>|&=+-'
cat search/*.js | sed 's#//.*##' |
	tr '\n\t' '  ' | sed -E 's# +# #g' |
	sed -E "s#([$JS_NOLETTER]) #\1#g" | sed -E "s# ([$JS_NOLETTER])#\1#g" |
	sed 's#^#\t<script defer>#' | sed 's#$#</script>\n#' >> include.html

# Template
echo -n "package data

// Code generated by build.bash DO NOT EDIT.

var index = \`
`sed -e '/<!--CODE-->/r include.html' -e '/<!--CODE-->/d' doc/data/index.gohtml`
\`
" > doc/data/index.go

rm include.html

# Build
go build
